return {
    ['Buttons'] = {
        ['Button_1'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/dgze cleric /rgl castaa "Purify Soul" $\\{Me.ID}',
            ['TextColorRGB'] = '36,231,219',
            ['Label'] = 'Purify ME',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_2'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '36,231,219',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Priest Radiant',
            ['Cmd'] = '/dgze priest /rgl castaa "radiant cure" $\\{Me.ID}',
        },
        ['Button_3'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Fellowship Registration Insignia',
            ['Cmd'] = '/ss /multiline ; /rgl stopcast ; /useitem "Fellowship Registration Insignia"',
            ['ShowLabel'] = false,
            ['TimerType'] = 'Item',
            ['Label'] = 'Fellowship Registration Insignia',
            ['Icon'] = '1678',
        },
        ['Button_4'] = {
            ['TextColorRGB'] = '220,212,16',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'RMP',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /rgl set RunMovePaused true',
            ['UpdateRate'] = 1,
            ['IconLua'] = '',
            ['ShowLabel'] = true,
        },
        ['Button_123'] = {
            ['Cooldown'] = 'Holy Guardian Discipline',
            ['TimerType'] = 'Disc',
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl usemap disc Guardian',
            ['Label'] = 'Guardian',
        },
        ['Button_122'] = {
            ['Cooldown'] = 'Armor of Zeal',
            ['Cmd'] = '/rgl usemap disc Armor',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Armor',
        },
        ['Button_124'] = {
            ['Cooldown'] = 'Holyforge Discipline',
            ['Cmd'] = '/rgl usemap disc Undeadburn',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Holy Forge',
        },
        ['Button_234'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '56,172,50',
            ['Cmd'] = '/ss /rgl set DoRez true',
            ['Label'] = 'Rez ON',
        },
        ['Button_226'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /dzquit',
            ['ShowLabel'] = true,
            ['Label'] = 'DZQuit',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_73'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Debuff ByCon',
            ['Cmd'] = '/ss /rgl set MobDebuff 2',
        },
        ['Button_8'] = {
            ['IconType'] = 'Item',
            ['ShowLabel'] = false,
            ['UpdateRate'] = 1,
            ['Label'] = 'Insig',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Fellowship Registration Insignia',
            ['Icon'] = 1678,
            ['IconLua'] = '',
            ['Cmd'] = '/ss /relocate fellow',
            ['TimerType'] = 'Item',
        },
        ['Button_235'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '187,82,126',
            ['Cmd'] = '/ss /rgl set DoRez false',
            ['ShowLabel'] = true,
            ['Label'] = 'Rez Off',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_74'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl set MobDebuff 1',
            ['Label'] = 'Debuff Off',
        },
        ['Button_204'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '36,231,219',
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge pal /rgl castaa "radiant cure" $\\{Me.ID}',
            ['Label'] = 'Paladin Radiant',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_21'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Drunkard\'s Stein',
            ['Icon'] = 208,
            ['Cmd'] = '/ss /relocate pok',
            ['ShowLabel'] = false,
            ['Label'] = 'Stein',
            ['TimerType'] = 'Item',
        },
        ['Button_213'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /removelev',
            ['Label'] = 'Rmv Lev',
        },
        ['Button_23'] = {
            ['Cooldown'] = 'Balefire Burst',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Label'] = 'Balefire Burst',
            ['Cmd'] = '/alt act 739',
        },
        ['Button_68'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Guard of Righteousness',
            ['ShowLabel'] = true,
            ['Icon'] = 128,
            ['TextColorRGB'] = '8,0,0',
            ['TimerType'] = 'Disc',
            ['Label'] = 'Guard',
            ['Cmd'] = '/rgl usemap disc GuardDisc',
        },
        ['Button_30'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Mythical Idol of the Stillmoon Conqueror',
            ['Cmd'] = '/rgl stopcast\n/rgl useitem "Mythical Idol of the Stillmoon Conqueror" ${Me.ID}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Item',
            ['Label'] = 'CotH',
            ['Icon'] = '1347',
        },
        ['Button_35'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/lua run makecrew\n/dex algarshm /lua run makecrew\n/dex algardru /lua run makecrew\n/timed 20 /mc ez1\n/timed 20 /dex algarshm /mc ez2\n/timed 20 /dex algardru /mc ez3\n/timed 40 /raidinvite Algarshm\n/timed 40 /raidinvite Algardru\n/timed 50 /dga /lua stop makecrew',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'EZ Raid',
            ['ShowLabel'] = true,
        },
        ['Button_268'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '43,158,147',
            ['Label'] = 'PAL Self Assist',
            ['Cmd'] = '/dex Algarpal /rgl assistup Algarpal\n/dex Algarpal /rgl set MAAggroScan true',
        },
        ['Button_230'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Stick Default',
            ['Cmd'] = '/ss /rgl set StickHow ""',
        },
        ['Button_280'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Protective Discipline',
            ['Icon'] = 82,
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl usemap disc Protective',
            ['Label'] = 'Protective Discipline',
            ['TimerType'] = 'Disc',
        },
        ['Button_41'] = {
            ['Cooldown'] = 'Armor of the Inquis.',
            ['Cmd'] = '/rgl castaa "Armor of the Inquisitor"',
            ['ShowLabel'] = true,
            ['Label'] = 'Armor AA',
            ['TimerType'] = 'AA',
        },
        ['Button_236'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '236,234,35',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'EVAC',
            ['Cmd'] = '/dge wiz /multiline ; /rgl stopcast ; /rgl castaa "Exodus"',
        },
        ['Button_22'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Quit Task',
            ['Cmd'] = '/ss /taskquit',
        },
        ['Button_60'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Timeless Larrikan\'s Mask',
            ['ShowLabel'] = true,
            ['Icon'] = '271',
            ['Cmd'] = '/useitem "Timeless Larrikan\'s Mask"',
            ['Label'] = 'Invis',
            ['TimerType'] = 'Item',
        },
        ['Button_19'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['ShowLabel'] = false,
            ['Icon'] = 7470,
            ['Cmd'] = '/multiline ; /timed 10 /windowstate FellowshipWnd open ; /timed 20 /nomodkey /notify FellowshipWnd FP_Subwindows tabselect 2 ; /timed 35 /nomodkey /notify FellowshipWnd FP_RefreshList leftmouseup ;\n/multiline ; /timed 50 /nomodkey /notify FellowshipWnd FP_CampsiteKitList listselect 1 ; /timed 65 /nomodkey /notify FellowshipWnd FP_DestroyCampsite leftmouseup ; /timed 80 /nomodkey /notify ConfirmationDialogBox Yes_Button leftmouseup ;\n/multiline ; /timed 100 /nomodkey /notify FellowshipWnd FP_CreateCampsite leftmouseup ; /timed 10 /windowstate FellowshipWnd close ;',
            ['Label'] = 'Campfire',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_245'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /multiline ; /target bank ; /timed 10 /target ${Target} ; /timed 25 /lns bankstuff',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'LNS Bank',
        },
        ['Button_237'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dga /rgl assistup Algarshd\n/dex Algarpal /rgl set MAAggroScan false',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Assist SHD All',
            ['TextColorRGB'] = '210,43,43',
        },
        ['Button_144'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['Icon'] = 22,
            ['ShowLabel'] = false,
            ['Label'] = 'Ground',
            ['Cmd'] = '/dex ${Target.CleanName} /itemtarget\n/timed 5 /dex ${Target.CleanName} /invoke $\\{Ground.Grab}\n/timed 10 /dex ${Target.CleanName} /autoinv\n/timed 15 /dex ${Target.CleanName} /invoke $\\{Window[InventoryWindow].DoClose}',
        },
        ['Button_103'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['Icon'] = 4408,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Shield Lock',
            ['Cmd'] = '/rgl set UseBandolier false\n/bandolier activate "Shield"',
        },
        ['Button_24'] = {
            ['Cooldown'] = 'Blessing Purification',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 9101',
            ['Label'] = 'Blessing Purification',
            ['TimerType'] = 'AA',
        },
        ['Button_39'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /makemevisible\n/ss /makemevisible\n/ss /makemevisible',
            ['TextColorRGB'] = '225,195,195',
            ['ShowLabel'] = true,
            ['Label'] = 'Visible',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_115'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Deflection Discipline',
            ['TimerType'] = 'Disc',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['Cmd'] = '/rgl usemap disc BlockDisc\n/bandolier activate Shield',
            ['Label'] = 'Block Disc',
            ['IconLua'] = '',
        },
        ['Button_111'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Gorgon Carapace',
            ['IconLua'] = '',
            ['Cmd'] = '/rgl usemap disc Carapace',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Carap.',
            ['UpdateRate'] = 1,
        },
        ['Button_63'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '218,159,58',
            ['Cmd'] = '/dex algarpal /rgl nohate ${Target.ID}',
            ['Label'] = 'PAL NoHate Target',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_227'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '199,125,23',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'BURN NOW',
            ['Cmd'] = '/ss /rgl burnnow ${Target.ID}',
        },
        ['Button_71'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Resistant Discipline',
            ['TimerType'] = 'Disc',
            ['Cmd'] = '',
            ['ShowLabel'] = true,
            ['Icon'] = 78,
            ['Label'] = 'Resistant Discipline',
        },
        ['Button_125'] = {
            ['Cooldown'] = 'Sanctification Discipline',
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl usemap disc Spellblock',
            ['Label'] = 'Sanct',
            ['TimerType'] = 'Disc',
        },
        ['Button_67'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '199,125,23',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '--lua\ncount = 30\nmax = count - 1\nmq.cmdf(\'/ss /multiline ; /rgl set DoAEDamage true ; /rgl set MezAECount 20 ; /rgl set MezStartCount 20 ; /rgl set MaxAETargetCnt 30\')',
            ['Label'] = 'AE MAX',
        },
        ['Button_89'] = {
            ['Cooldown'] = 'Beacon of the Righteous',
            ['Cmd'] = '/rgl castaa "Beacon of the Righteous"',
            ['ShowLabel'] = true,
            ['Label'] = 'Beacon',
            ['TimerType'] = 'AA',
        },
        ['Button_225'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dge caster /rgl set StickHow "20 behindonce !front moveback uw"\n/dge priest /rgl set StickHow "20 behindonce !front moveback uw"\n/dge melee /rgl set StickHow "20 behindonce !front moveback uw"\n/dga tank /rgl set StickHow "20 moveback uw"',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Stick 20',
        },
        ['Button_51'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Chase Off',
            ['Cmd'] = '/ss /rgl chaseoff',
        },
        ['Button_37'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /assist ${Me.CleanName}\n/ss /face fast\n/ss /attack on\n/ss /pet attack\n',
            ['ShowLabel'] = true,
            ['Label'] = 'Manual Assist',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_58'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Rampart Discipline',
            ['Cmd'] = '/disc Rampart Discipline',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Rampart Discipline',
            ['Icon'] = 77,
        },
        ['Button_191'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/removebuff cloak of\n/timed 1 /removebuff Voice of Innoruuk\n/timed 2 /dgza /removebuff Circle of Fireskin\n/timed 3 /dgza /removebuff Guard of the Earth\n/timed 4 /dgza /removebuff Inferno Ward\n/timed 5 /dgza /removebuff Fireskin\n/timed 6 /dgza /removebuff Shield of Torment',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Drop DS',
        },
        ['Button_200'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '36,231,219',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/dgze pal /rgl castaa "Beacon of the Righteous"',
            ['Label'] = 'PAL Beacon Now',
        },
        ['Button_59'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Sanctification Discipline',
            ['TimerType'] = 'Disc',
            ['Icon'] = 46,
            ['ShowLabel'] = true,
            ['Label'] = 'Sanctification Discipline',
            ['Cmd'] = '/disc Sanctification Discipline',
        },
        ['Button_246'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /multiline ; /target ${Target} ; /timed 10 /lns sellstuff',
            ['ShowLabel'] = true,
            ['Label'] = 'LNS Sell',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_26'] = {
            ['Cooldown'] = 'Divine Call',
            ['Cmd'] = '/alt act 660',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Divine Call',
        },
        ['Button_34'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/grouproles set ${Me.DisplayName} 1\n/grouproles set ${Me.DisplayName} 2',
            ['Label'] = 'Group Roles',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_12'] = {
            ['Cooldown'] = 'Ageless Enmity',
            ['Cmd'] = '/alt act 10392',
            ['ShowLabel'] = true,
            ['Label'] = 'Ageless Enmity',
            ['TimerType'] = 'AA',
        },
        ['Button_109'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge brd /rgl stopcast\n/dge brd /rgl usemap song CalmSong ${Target}',
            ['Label'] = 'BRD Calm',
        },
        ['Button_272'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['Cmd'] = '/rgl disablerotation "HateTools(AggroTarget)"\n/rgl disablerotation "HateTools(AutoTarget)"\n/rgl disablerotation "AEHateTools"',
            ['ShowLabel'] = true,
            ['Label'] = 'SHD Hate OFF',
            ['TextColorRGB'] = '199,76,76',
        },
        ['Button_155'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Artifact of Dread Gaze',
            ['TimerType'] = 'Item',
            ['EvaluateLabel'] = false,
            ['IconLua'] = '',
            ['Icon'] = '2498',
            ['ShowLabel'] = false,
            ['Cmd'] = '/useitem "Artifact of Dread Gaze"',
            ['Label'] = 'Artifact of Dread Gaze',
            ['UpdateRate'] = 1,
        },
        ['Button_126'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 10,
            ['TimerType'] = 'Seconds Timer',
            ['Cmd'] = '-- lua\nlocal count = mq.TLO.Group.Members()\nfor i = 1, count do\n    if not mq.TLO.Group.Member(i).OtherZone() then\n        local class = mq.TLO.Group.Member(i).Class.ShortName():lower()\n        local name = mq.TLO.Group.Member(i).DisplayName()\n        if class == "brd" then\n            mq.cmdf(\'/multiline ; /dex %s /alt act 3704 ; /timed 2 /dex %s /stopsong ; /timed 8 /dex %s /alt act 231\', name, name, name)\n            break\n        end\n    end\nend',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['Label'] = 'Bard Invis',
            ['IconLua'] = '',
        },
        ['Button_28'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/rgl say ready',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Ready',
        },
        ['Button_66'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dex algarshm /rgl usemap spell SnareHot ${Me.ID}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['TextColorRGB'] = '198,239,53',
            ['Label'] = 'Shaman Torpor',
        },
        ['Button_52'] = {
            ['Cooldown'] = 'Balefire Burst',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Balefire Burst',
            ['Cmd'] = '/alt act 739',
        },
        ['Button_61'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge dru /rgl usemap spell "ReptileBuff" ${Me.ID}',
            ['TextColorRGB'] = '198,239,53',
            ['Label'] = 'Reptile',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_143'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/itemtarget\n/timed 5 /invoke ${Ground.Grab}\n/timed 10 /autoinv\n/timed 15 /invoke ${Window[InventoryWindow].DoClose}',
            ['Label'] = 'Self Grab',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_215'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /lua stop rgmercs\n/alertmaster off\n/ss /autoinventory',
            ['ShowLabel'] = true,
            ['Label'] = 'Unload RGL',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_145'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['Icon'] = 885,
            ['ShowLabel'] = false,
            ['Cmd'] = '/dgza /autoinventory\n/timed 5 /dgza /doortarget\n/timed 10 /dgza /click left door',
            ['Label'] = 'Door',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_161'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['Cmd'] = '--lua\nlocal cmd= mq.TLO.Raid.Members() > 0 and "dgre" or "dgge"\nmq.cmdf("/%s /lns unpause", cmd)',
            ['TextColorRGB'] = '192,11,195',
            ['ShowLabel'] = true,
            ['Label'] = 'LNS Others',
        },
        ['Button_42'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Blood Drinker\'s Coating',
            ['Cmd'] = '/rgl useitem "Blood Drinker\'s Coating"',
            ['ShowLabel'] = false,
            ['TimerType'] = 'Item',
            ['Label'] = 'Blood Drinker\'s Coating',
            ['Icon'] = '2585',
        },
        ['Button_281'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Guardian of the Battlefield Discipline',
            ['Cmd'] = '/disc Guardian of the Battlefield Discipline',
            ['TimerType'] = 'Disc',
            ['ShowLabel'] = true,
            ['Label'] = 'Guardian of the Battlefield Discipline',
            ['Icon'] = 82,
        },
        ['Button_202'] = {
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Mantle',
            ['Timer'] = '',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Ichor Guard',
            ['ToggleCheck'] = '',
            ['Cmd'] = '/rgl usemap disc Mantle',
            ['IconLua'] = '',
        },
        ['Button_116'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Leechcurse Discipline',
            ['Cmd'] = '/rgl usemap disc LeechCurse',
            ['TimerType'] = 'Disc',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['IconLua'] = '',
            ['Label'] = 'Leech Curse',
        },
        ['Button_117'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Unholy Aura Discipline',
            ['Cmd'] = '/rgl usemap disc UnholyAura',
            ['UpdateRate'] = 1,
            ['IconLua'] = '',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Unholy Aura',
        },
        ['Button_167'] = {
            ['IconType'] = 'Item',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['TimerType'] = 'Item',
            ['Label'] = 'Epic',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Innoruuk\'s Dark Wrath',
            ['Icon'] = 1019,
            ['IconLua'] = '',
            ['Cmd'] = '/rgl useitem "Innoruuk\'s Dark Wrath"',
        },
        ['Button_276'] = {
            ['Cooldown'] = 'Forage',
            ['TimerType'] = 'Ability',
            ['ShowLabel'] = true,
            ['Cmd'] = '/doability Forage',
            ['Label'] = 'Forage',
        },
        ['Button_140'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /yes',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'YES',
        },
        ['Button_141'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /autoinventory',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Auto Inv',
        },
        ['Button_45'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/lua run makecrew\n/timed 20 /makecrew lazpal\n/timed 100 /lua stop makecrew',
            ['Label'] = 'Laz Caster',
        },
        ['Button_44'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Dusty Fishbone Earring',
            ['Icon'] = '22',
            ['ShowLabel'] = false,
            ['TimerType'] = 'Item',
            ['Label'] = 'Dusty Fishbone Earring',
            ['Cmd'] = '/useitem "Dusty Fishbone Earring"',
        },
        ['Button_231'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Xeno\'s Faceguard',
            ['Cmd'] = '/useitem "Xeno\'s Faceguard"',
            ['ShowLabel'] = false,
            ['Icon'] = '3181',
            ['TimerType'] = 'Item',
            ['Label'] = 'Xeno\'s Faceguard',
        },
        ['Button_184'] = {
            ['Cooldown'] = 'Radiant Cure',
            ['Cmd'] = '/rgl castaa "radiant cure" ${Me.ID}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Radiant Cure',
        },
        ['Button_32'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '237,55,55',
            ['Cmd'] = '/ss /rgl set BurnAuto on',
            ['Label'] = 'Burn ON',
        },
        ['Button_33'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl set BurnAuto off',
            ['Label'] = 'Burn Off',
            ['TextColorRGB'] = '197,209,28',
        },
        ['Button_282'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Mythical Golden Ancestors Symbol',
            ['ShowLabel'] = true,
            ['Cmd'] = '/useitem "Mythical Golden Ancestors Symbol"',
            ['TextColorRGB'] = '8,2,2',
            ['Icon'] = '1579',
            ['Label'] = 'Feign',
            ['TimerType'] = 'Item',
        },
        ['Button_220'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dex algardru /alt act 939\n/timed 3 /dex Algarenc /target ${Me.DisplayName}\n/timed 4 /dex Algarenc /alt act 1210\n/timed 5 /dex Algarnec /target ${Me.DisplayName}\n/timed 6 /dex Algarnec /alt activate 1212\n/timed 5 /dex Algarclr /target ${Me.DisplayName}\n/timed 6 /dex Algarclr /alt activate 1212',
            ['TextColorRGB'] = '112,118,224',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Invis',
        },
        ['Button_56'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Mythical Bracer of the Bloody Void',
            ['Icon'] = '1624',
            ['ShowLabel'] = true,
            ['Cmd'] = '/useitem "Mythical Bracer of the Bloody Void"',
            ['Label'] = 'Invis',
            ['TimerType'] = 'Item',
        },
        ['Button_185'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '198,239,53',
            ['Cmd'] = '/dge clr /rgl usemap spell GroupElixir $\\{Me.ID}\n/dge shm /rgl usemap spell GroupRenewalHoT $\\{Me.ID}',
            ['Label'] = 'Elixir/ GrpHoT',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_55'] = {
            ['Cooldown'] = 'Speed of the Savior',
            ['Cmd'] = '/alt act 659',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Label'] = 'Speed of the Savior',
        },
        ['Button_277'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dgza /rgl forcetarget ${Target.ID}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Force My Target',
        },
        ['Button_138'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '242,41,41',
            ['Cmd'] = '/ss /rgl pause\n/ss /autoinv\n/ss /attack off\n/dgze nec /rgl stoplich\n/ss /rgl set runmovepaused false',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Pause ALL',
        },
        ['Button_139'] = {
            ['TextColorRGB'] = '76,234,28',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Resume ALL',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 0,
            ['IconLua'] = '',
            ['UpdateRate'] = 1,
            ['Cmd'] = '/ss /rgl unpause\n/ss /rgl set RunMovePaused false\n/dgze brd /stopsong',
            ['ShowLabel'] = true,
        },
        ['Button_192'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '--lua\ncount = mq.TLO.MacroQuest.BuildName() == "Emu" and 11 or 6\nmax = count - 1\nmq.cmdf(\'/ss /multiline ; /rgl set DoAEDamage true ; /rgl set MezAECount %s ; /rgl set MezStartCount %s ; /rgl set MaxAETargetCnt %s\', count, count, max)',
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '231,55,55',
            ['Label'] = 'AE ON',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_193'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '103,171,55',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'AE Off',
            ['Cmd'] = '/ss /rgl set DoAEDamage false\n/ss /rgl set MezAECount 3\n/ss /rgl set MezStartCount 2',
        },
        ['Button_62'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 'Deflection Discipline',
            ['Icon'] = 77,
            ['TimerType'] = 'Disc',
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl usemap disc BlockDisc ${Me.ID}\n/bandolier activate Shield',
            ['Label'] = 'BlockDisc',
        },
        ['Button_273'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '-- lua\nfor i = 1, mq.TLO.Me.MaxBuffSlots() do\nlocal buff = mq.TLO.Me.Buff(i)\nif buff() ~= nil and buff.Duration.Minutes() < 4 then\nbuff.Remove()\nend\nend\n\n',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Remove Fading Buffs',
        },
        ['Button_162'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['TextColorRGB'] = '36,231,219',
            ['Cmd'] = '/dge dru /rgl castaa "radiant cure" $\\{Me.ID}',
            ['Label'] = 'Druid Radiant',
            ['ShowLabel'] = true,
        },
        ['Button_164'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge clr /rgl castaa "radiant cure" $\\{Me.ID}',
            ['Label'] = 'Cleric Radiant',
            ['TextColorRGB'] = '36,231,219',
        },
        ['Button_183'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge shm /rgl castaa "radiant cure" $\\{Me.ID}',
            ['Label'] = 'Shaman Radiant',
            ['TextColorRGB'] = '36,231,219',
        },
        ['Button_40'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Dawnseeker\'s Chestpiece of the Defender',
            ['TimerType'] = 'Item',
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl useitem "Dawnseeker\'s Chestpiece of the Defender"',
            ['TextColorRGB'] = '11,11,11',
            ['Label'] = 'OoW',
            ['Icon'] = '124',
        },
        ['Button_210'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Resume ME',
            ['Cmd'] = '/rgl unpause',
        },
        ['Button_209'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '206,122,37',
            ['Cmd'] = '/rgl pause',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Pause ME',
        },
        ['Button_65'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl castaa "Voice of Thule" ${Me.ID}',
            ['Label'] = 'Voice of Thule',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_31'] = {
            ['IconType'] = 'Spell',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Blade',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Whirlwind Blade',
            ['IconLua'] = '',
            ['Icon'] = 91,
            ['Cmd'] = '/rgl usemap disc BladeDisc',
            ['UpdateRate'] = 1,
        },
        ['Button_271'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['TextColorRGB'] = '213,222,84',
            ['Cmd'] = '/rgl enablerotation "HateTools(AggroTarget)"\n/rgl enablerotation "HateTools(AutoTarget)"\n/rgl enablerotation "AEHateTools"',
            ['Label'] = 'SHD Hate ON',
        },
        ['Button_64'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/rgl disablerotation "AEHateTools"',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'SHD AEHate OFF',
            ['TextColorRGB'] = '230,138,31',
        },
        ['Button_269'] = {
            ['Cooldown'] = 0,
            ['TextColorRGB'] = '56,167,104',
            ['TimerType'] = 'Seconds Timer',
            ['Cmd'] = '--lua\nif mq.TLO.Me.Name() == "Algarpal" then\nmq.cmd(\'/multiline ; /rgl enablerotation "HateTools(AggroTarget)" ; /rgl enablerotation "AEHateTools" ; /rgl enablerotation "HateTools(AutoTarget)"\')\nelse\nmq.cmd(\'/dex Algarpal /rgl enablerotation "HateTools(AggroTarget)"\')\nmq.cmd(\'/dex Algarpal /rgl enablerotation "HateTools(AutoTarget)"\')\nmq.cmd(\'/dex Algarpal /rgl enablerotation "AEHateTools"\')\nmq.cmd(\'/dex Algarpal /rgl set DoBattleRez false\')\nend',
            ['ShowLabel'] = true,
            ['Label'] = 'PAL Hate ON',
        },
        ['Button_270'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['TextColorRGB'] = '133,87,179',
            ['Cmd'] = '/dex Algarpal /rgl disablerotation "HateTools(AggroTarget)"\n/dex Algarpal /rgl disablerotation "HateTools(AutoTarget)"\n/dex Algarpal /rgl disablerotation "AEHateTools"\n/dex Algarpal /rgl set DoBattleRez true',
            ['Label'] = 'PAL Hate OFF',
        },
        ['Button_36'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = '7',
        },
        ['Button_49'] = {
            ['Cooldown'] = 'Force Rejuv',
            ['Cmd'] = '/alt act 7003',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Force Rejuv',
        },
        ['Button_80'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/dex algarwar /nav spawn algarshd\n/dex algarpal /nav spawn algarshd',
            ['Label'] = 'Tank Stack',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_48'] = {
            ['Cooldown'] = 'Harmshield',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Harm Shield',
            ['Cmd'] = '/alt act 821',
        },
        ['Button_242'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '93,156,190',
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Assist PAL Others',
            ['Cmd'] = '/dge /rgl assistup Algarpal\n/dex Algarpal /rgl set MAAggroScan false',
        },
        ['Button_46'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /pet back off',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Pet Back Off',
        },
        ['Button_38'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Might Melee',
            ['Cmd'] = '/mc might1\n/dex algarshm /lua run makecrew\n/timed 10 /dex algarshm /mc might2\n/timed 30 /raidinvite Algarshm',
        },
        ['Button_57'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 0,
            ['Cmd'] = '--lua\n--translate face into heading commands\nlocal heading = mq.TLO.Me.Heading.Degrees()\nlocal face = heading\nif heading > 0 and heading < 180 then face = -heading\nelseif heading > 180 then face = 360 - heading\nend\nmq.cmdf("/dgze /face fast heading %d", face)\nmq.cmd("/dgza /keypress forward hold")\n',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['IconLua'] = '',
            ['Label'] = 'GAYLY FWD',
        },
        ['Button_194'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /xtarg set 1 ET\n/timed 5 /ss /xtarg set 1 AH\n/ss /xtarg set 2 ET\n/timed 5 /ss /xtarg set 2 AH\n/ss /xtarg set 3 ET\n/timed 5 /ss /xtarg set 3 AH\n/ss /xtarg set 4 ET\n/timed 5 /ss /xtarg set 4 AH\n/ss /xtarg set 5 ET\n/timed 5 /ss /xtarg set 5 AH\n/ss /xtarg set 6 ET\n/timed 5 /ss /xtarg set 6 AH\n/ss /xtarg set 7 ET\n/timed 5 /ss /xtarg set 7 AH\n/ss /xtarg set 8 ET\n/timed 5 /ss /xtarg set 8 AH\n/ss /xtarg set 9 ET\n/timed 5 /ss /xtarg set 9 AH\n/ss /xtarg set 10 ET\n/timed 5 /ss /xtarg set 10 AH\n/ss /xtarg set 11 ET\n/timed 5 /ss /xtarg set 11 AH\n/ss /xtarg set 12 ET\n/timed 5 /ss /xtarg set 12 AH',
            ['Label'] = 'Xtarg Fix',
        },
        ['Button_173'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /rgl stopcast\n/timed 5 /ss /rgl castaa "freeport temple" $/{Me.ID}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Freeport Temple',
        },
        ['Button_87'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/dgza /stopcast\n/timed 5 /dgza /alt act 331',
            ['Label'] = 'Origin',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_267'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Gate',
            ['Cmd'] = '/ss /rgl stopcast\n/ss /rgl castaa gate $\\{Me.ID}',
        },
        ['Button_171'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/rgl rsay Hail, ${Target.CleanName}',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Hail Target',
        },
        ['Button_114'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Unholy Guardian Discipline',
            ['Cmd'] = '/rgl usemap disc Guardian',
            ['IconLua'] = '',
            ['UpdateRate'] = 1,
            ['ShowLabel'] = true,
            ['TimerType'] = 'Disc',
            ['Label'] = 'Guardian',
        },
        ['Button_142'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'Close All',
            ['Cmd'] = '/ss /cleanup',
        },
        ['Button_112'] = {
            ['Cooldown'] = 'Withstand',
            ['ShowLabel'] = true,
            ['Cmd'] = '/rgl usemap disc MeleeMit',
            ['Label'] = 'Melee Mit',
            ['TimerType'] = 'Disc',
        },
        ['Button_16'] = {
            ['Cooldown'] = 'Shield Flash',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 1112',
            ['Label'] = 'Shield Flash',
            ['TimerType'] = 'AA',
        },
        ['Button_18'] = {
            ['Cooldown'] = 'Armor of Experience',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 2000',
            ['Label'] = 'Armor of Experience',
        },
        ['Button_275'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['Cmd'] = '/ss /rgl cleartempall',
            ['ShowLabel'] = true,
            ['Label'] = 'Clear Temps',
        },
        ['Button_146'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /multiline ; /lua run rgmercs ; /timed 50 /rgl unpause ; /timed 100 /rgl chaseon ${Me.CleanName}',
            ['Label'] = 'Load RGL',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_156'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /rgl campon',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'Camp On',
        },
        ['Button_157'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl chaseon ${Me.CleanName}',
            ['Label'] = 'Chase On',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_249'] = {
            ['Cooldown'] = '481',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl stopcast\n/ss /rgl castaa "Lesson of the Devoted"',
            ['Label'] = 'Lesson',
        },
        ['Button_266'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/dge tank /rgl set ChaseDistance 25\n/dge tank /rgl set ChaseStopDistance 20\n/dge melee /rgl set ChaseDistance 30\n/dge melee /rgl set ChaseStopDistance 25\n/dge caster /rgl set ChaseDistance 50\n/dge caster /rgl set ChaseStopDistance 45\n/dge priest /rgl set ChaseDistance 50\n/dge priest /rgl set ChaseStopDistance 45\n/dgza /rgl set AssistRange 150',
            ['Label'] = 'Chase Stagger',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_70'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /rgl set ChaseDistance 18\n/ss /rgl set ChaseStopDistance 15\n/ss /rgl set AssistRange 118',
            ['ShowLabel'] = true,
            ['Label'] = 'Chase 18',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_43'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl set ChaseDistance 33\n/ss /rgl set ChaseStopDistance 25\n/ss /rgl set AssistRange 133',
            ['Label'] = 'Chase 33',
        },
        ['Button_159'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl set ChaseDistance 50\n/ss /rgl set ChaseStopDistance 40\n/ss /rgl set AssistRange 150',
            ['Label'] = 'Chase 50',
        },
        ['Button_127'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dge wiz /rgl stopcast\n/dge wiz /rgl castaa "Teleport"',
            ['ShowLabel'] = true,
            ['Label'] = 'Teleport',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_9'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = '511',
            ['Icon'] = 12047,
            ['Cmd'] = '/ss /rgl stopcast\n/ss /rgl pause\n/timed 5 /ss /relocate lobby\n',
            ['ShowLabel'] = false,
            ['TimerType'] = 'AA',
            ['Label'] = 'Throne',
        },
        ['Button_274'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/ss /rgl tempset DoAutoStick false',
            ['Label'] = 'Stick Temp OFF',
        },
        ['Button_50'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = false,
            ['Cmd'] = '/ss /useitem "Jann\'s Veil"\n/timed 25 /ss /removebuff "Illusion: Djinn Soldier"\n/timed 25 /ss /removebuff "Illusion: Duende Scholar"\n/timed 25 /ss /removebuff "Illusion: Efreeti Amir"',
            ['Label'] = 'Veil',
            ['Icon'] = 3175,
        },
        ['Button_47'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 0,
            ['Icon'] = 8344,
            ['ShowLabel'] = false,
            ['Cmd'] = '/ss /useitem "Emperor Ganak Familiar"\n/timed 45 /ss /removebuff "Summon Familiar: Emperor Ganak"',
            ['Label'] = 'Familiar',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_20'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Cmd'] = '/lua run makecrew\n/timed 20 /mc test1\n/timed 50 /lua stop makecrew',
            ['Label'] = 'Test Main',
        },
        ['Button_244'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /lns cleanup',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Seconds Timer',
            ['Label'] = 'LNS Cleanup',
        },
        ['Button_11'] = {
            ['IconType'] = 'Spell',
            ['Cooldown'] = 5,
            ['TimerType'] = 'Spell Gem',
            ['Cmd'] = '/cast 5',
            ['ShowLabel'] = true,
            ['Label'] = 'For Power',
        },
        ['Button_5'] = {
            ['Cooldown'] = 'Hate\'s Attraction',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Label'] = 'Hate\'s Attraction',
            ['Cmd'] = '/alt act 9400',
        },
        ['Button_10'] = {
            ['Cooldown'] = 'Stream of Hatred',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 731',
            ['Label'] = 'Stream of Hatred',
        },
        ['Button_198'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/ss /lns pause',
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '20,104,131',
            ['Label'] = 'LNS Pause',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_7'] = {
            ['Cooldown'] = 'Reaver Bargain',
            ['Cmd'] = '/alt act 1116',
            ['ShowLabel'] = true,
            ['Label'] = 'Reaver Bargain',
            ['TimerType'] = 'AA',
        },
        ['Button_6'] = {
            ['Cooldown'] = 'Leech Touch',
            ['TimerType'] = 'AA',
            ['Cmd'] = '/alt act 87',
            ['ShowLabel'] = true,
            ['Label'] = 'Leech Touch',
        },
        ['Button_17'] = {
            ['Cooldown'] = 'Unbridled Strike',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 771',
            ['Label'] = 'Unbridled Strike',
        },
        ['Button_53'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Explosion of Hatred',
            ['IconLua'] = '',
            ['UpdateRate'] = 1,
            ['Cmd'] = '/alt act 822',
            ['ShowLabel'] = true,
            ['Label'] = 'Expl.of Hatred',
            ['TimerType'] = 'AA',
        },
        ['Button_54'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Explosion of Spite',
            ['Cmd'] = '/alt act 749',
            ['ShowLabel'] = true,
            ['UpdateRate'] = 1,
            ['IconLua'] = '',
            ['Label'] = 'Expl.of Spite',
            ['TimerType'] = 'AA',
        },
        ['Button_25'] = {
            ['Cooldown'] = 'Champion Oath',
            ['Cmd'] = '/alt act 1119',
            ['ShowLabel'] = true,
            ['Label'] = 'Champion Oath',
            ['TimerType'] = 'AA',
        },
        ['Button_214'] = {
            ['IconType'] = 'Item',
            ['ShowLabel'] = false,
            ['TimerType'] = 'Item',
            ['Label'] = 'Compass of the Hive Summoner',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Compass of the Hive Summoner',
            ['UpdateRate'] = 1,
            ['Icon'] = '250',
            ['Cmd'] = '/useitem "Compass of the Hive Summoner"',
            ['IconLua'] = '',
        },
        ['Button_166'] = {
            ['IconType'] = 'Item',
            ['ShowLabel'] = true,
            ['Label'] = 'Feign',
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Legendary Fabled Blood Ember Greaves',
            ['TimerType'] = 'Item',
            ['UpdateRate'] = 1,
            ['Icon'] = '40',
            ['Cmd'] = '/useitem "Legendary Fabled Blood Ember Greaves"',
            ['IconLua'] = '',
        },
        ['Button_216'] = {
            ['Cooldown'] = '821',
            ['TimerType'] = 'AA',
            ['Cmd'] = '/alt act 821',
            ['ShowLabel'] = true,
            ['Label'] = 'Harm Shield',
        },
        ['Button_203'] = {
            ['Cooldown'] = 0,
            ['Cmd'] = '/dgze shm /rgl castaa "Turgur\'s Swarm"',
            ['TimerType'] = 'Seconds Timer',
            ['ShowLabel'] = true,
            ['Label'] = 'SHM Slow',
        },
        ['Button_29'] = {
            ['Cooldown'] = 0,
            ['TimerType'] = 'Seconds Timer',
            ['TextColorRGB'] = '237,156,17',
            ['ShowLabel'] = true,
            ['Cmd'] = '--lua\ncount = mq.TLO.MacroQuest.BuildType == "Emu" and 6 or 4\nmax = count - 1\nmq.cmdf("/multiline ; /ss /rgl set DoAEDamage true ; /ss /rgl set MezAECount %s ; /ss /rgl set MezStartCount %s ; /ss/rgl set MaxAETargetCnt %s ", count, count, max)',
            ['Label'] = 'AE Kinda On',
        },
        ['Button_224'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Sikl\'s Bloodied Greaves',
            ['Icon'] = '1081',
            ['TimerType'] = 'Item',
            ['ShowLabel'] = true,
            ['Cmd'] = '/useitem "Sikl\'s Bloodied Greaves"',
            ['Label'] = 'Poison',
        },
        ['Button_217'] = {
            ['EvaluateLabel'] = false,
            ['Cooldown'] = 'Fabled Staff of Forbidden Rites',
            ['IconLua'] = '',
            ['Cmd'] = '/useitem "Fabled Staff of Forbidden Rites"',
            ['IconType'] = 'Item',
            ['ShowLabel'] = false,
            ['Icon'] = '387',
            ['TimerType'] = 'Item',
            ['Label'] = 'Fabled Staff of Forbidden Rites',
            ['UpdateRate'] = 1,
        },
        ['Button_13'] = {
            ['Cooldown'] = 'Death\'s Effigy',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 7756',
            ['Label'] = 'Death\'s Effigy',
        },
        ['Button_14'] = {
            ['Cooldown'] = 'Death Peace',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Death Peace',
            ['Cmd'] = '/alt act 428',
        },
        ['Button_15'] = {
            ['Cooldown'] = 'Hate Step',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Hate Step',
            ['Cmd'] = '/alt act 824',
        },
        ['Button_208'] = {
            ['Cooldown'] = 'Encroaching Darkness',
            ['Cmd'] = '/alt act 826',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Encroaching Darkness',
        },
        ['Button_264'] = {
            ['Cooldown'] = 'Cloak of Shadows',
            ['TimerType'] = 'AA',
            ['ShowLabel'] = true,
            ['Cmd'] = '/alt act 531',
            ['Label'] = 'Cloak of Shadows',
        },
        ['Button_88'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['Cmd'] = '/lua run makecrew\n/dex algardru /lua run makecrew\n/timed 20 /mc might3\n/timed 20 /dex algardru /mc might4\n/timed 40 /raidinvite Algardru\n/timed 50 /dga /lua stop makecrew',
            ['Label'] = 'Might Casters',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_90'] = {
            ['IconType'] = 'Item',
            ['Cooldown'] = 'Plate Chestguard of the Helpless (Tier 1)',
            ['Icon'] = '124',
            ['Cmd'] = '/rgl useitem "PLate Chestguard of the Helpless (Tier 1)"',
            ['ShowLabel'] = true,
            ['TimerType'] = 'Item',
            ['Label'] = 'RC Item',
        },
        ['Button_197'] = {
            ['Cooldown'] = 0,
            ['ShowLabel'] = true,
            ['TextColorRGB'] = '164,44,165',
            ['Cmd'] = '/ss /lns unpause',
            ['Label'] = 'LNS Resume',
            ['TimerType'] = 'Seconds Timer',
        },
        ['Button_27'] = {
            ['Cooldown'] = 'Marr\'s Gift',
            ['Cmd'] = '/alt act 1282',
            ['ShowLabel'] = true,
            ['TimerType'] = 'AA',
            ['Label'] = 'Marr\'s Gift',
        },
    },
    ['Sets'] = {
        ['EQM Tank'] = {
            [14] = 'Button_242',
            [2] = 'Button_272',
            [5] = 'Button_270',
            [12] = 'Button_80',
            [11] = 'Button_34',
            [4] = 'Button_269',
            [8] = 'Button_63',
            [3] = 'Button_64',
            [7] = 'Button_200',
            [1] = 'Button_271',
            [15] = 'Button_268',
            [13] = 'Button_237',
        },
        ['SHD EQM'] = {
            [34] = 'Button_30',
            [2] = 'Button_53',
            [31] = 'Button_13',
            [12] = 'Button_65',
            [45] = 'Button_87',
            [9] = 'Button_49',
            [7] = 'Button_36',
            [1] = 'Button_31',
            [40] = 'Button_264',
            [36] = 'Button_15',
            [4] = 'Button_155',
            [32] = 'Button_14',
            [51] = 'Button_90',
            [5] = 'Button_231',
            [47] = 'Button_88',
            [26] = 'Button_224',
            [3] = 'Button_54',
            [43] = 'Button_48',
            [33] = 'Button_282',
            [30] = 'Button_217',
            [20] = 'Button_203',
            [18] = 'Button_216',
            [22] = 'Button_191',
            [16] = 'Button_166',
            [15] = 'Button_214',
            [38] = 'Button_208',
        },
        ['Laz'] = {
            [2] = 'Button_194',
            [31] = 'Button_37',
            [11] = 'Button_144',
            [41] = 'Button_197',
            [9] = 'Button_141',
            [19] = 'Button_266',
            [1] = 'Button_57',
            [40] = 'Button_246',
            [39] = 'Button_245',
            [20] = 'Button_70',
            [16] = 'Button_156',
            [38] = 'Button_244',
            [14] = 'Button_275',
            [12] = 'Button_145',
            [45] = 'Button_44',
            [25] = 'Button_230',
            [21] = 'Button_43',
            [44] = 'Button_45',
            [6] = 'Button_171',
            [4] = 'Button_87',
            [30] = 'Button_215',
            [27] = 'Button_274',
            [3] = 'Button_173',
            [43] = 'Button_161',
            [8] = 'Button_142',
            [26] = 'Button_225',
            [22] = 'Button_159',
            [17] = 'Button_51',
            [5] = 'Button_267',
            [18] = 'Button_157',
            [10] = 'Button_143',
            [42] = 'Button_198',
            [15] = 'Button_146',
            [7] = 'Button_140',
        },
        ['PAL EQM'] = {
            [34] = 'Button_52',
            [32] = 'Button_30',
            [5] = 'Button_231',
            [12] = 'Button_115',
            [35] = 'Button_60',
            [31] = 'Button_282',
            [2] = 'Button_89',
            [7] = 'Button_184',
            [1] = 'Button_31',
            [36] = 'Button_55',
            [38] = 'Button_56',
        },
        ['EQM'] = {
            [2] = 'Button_194',
            [31] = 'Button_37',
            [11] = 'Button_144',
            [41] = 'Button_197',
            [9] = 'Button_141',
            [23] = 'Button_225',
            [19] = 'Button_266',
            [1] = 'Button_57',
            [40] = 'Button_246',
            [39] = 'Button_245',
            [20] = 'Button_70',
            [16] = 'Button_156',
            [38] = 'Button_244',
            [14] = 'Button_275',
            [12] = 'Button_145',
            [45] = 'Button_38',
            [25] = 'Button_274',
            [35] = 'Button_46',
            [8] = 'Button_142',
            [44] = 'Button_88',
            [6] = 'Button_171',
            [24] = 'Button_230',
            [30] = 'Button_215',
            [5] = 'Button_267',
            [3] = 'Button_173',
            [43] = 'Button_161',
            [10] = 'Button_143',
            [27] = 'Button_213',
            [22] = 'Button_159',
            [4] = 'Button_87',
            [21] = 'Button_43',
            [18] = 'Button_51',
            [17] = 'Button_157',
            [42] = 'Button_198',
            [15] = 'Button_146',
            [7] = 'Button_140',
        },
        ['Laz Util'] = {
            [14] = 'Button_138',
            [2] = 'Button_33',
            [29] = 'Button_209',
            [10] = 'Button_66',
            [23] = 'Button_162',
            [8] = 'Button_185',
            [7] = 'Button_213',
            [1] = 'Button_32',
            [6] = 'Button_39',
            [30] = 'Button_4',
            [25] = 'Button_183',
            [28] = 'Button_210',
            [26] = 'Button_204',
            [18] = 'Button_67',
            [24] = 'Button_164',
            [22] = 'Button_1',
            [17] = 'Button_193',
            [20] = 'Button_273',
            [3] = 'Button_227',
            [5] = 'Button_220',
            [16] = 'Button_192',
            [15] = 'Button_139',
            [12] = 'Button_277',
        },
        ['EZ'] = {
            [2] = 'Button_194',
            [31] = 'Button_37',
            [11] = 'Button_144',
            [27] = 'Button_213',
            [23] = 'Button_225',
            [19] = 'Button_266',
            [1] = 'Button_57',
            [40] = 'Button_246',
            [24] = 'Button_230',
            [20] = 'Button_70',
            [16] = 'Button_156',
            [38] = 'Button_244',
            [14] = 'Button_275',
            [12] = 'Button_145',
            [45] = 'Button_35',
            [10] = 'Button_143',
            [21] = 'Button_43',
            [7] = 'Button_140',
            [6] = 'Button_171',
            [30] = 'Button_215',
            [39] = 'Button_245',
            [41] = 'Button_197',
            [43] = 'Button_161',
            [25] = 'Button_274',
            [18] = 'Button_51',
            [22] = 'Button_159',
            [4] = 'Button_87',
            [5] = 'Button_267',
            [3] = 'Button_173',
            [17] = 'Button_157',
            [42] = 'Button_198',
            [15] = 'Button_146',
            [8] = 'Button_142',
        },
        ['SHD Disc EQM'] = {
            [5] = 'Button_117',
            [3] = 'Button_115',
            [11] = 'Button_276',
            [4] = 'Button_116',
            [1] = 'Button_202',
            [6] = 'Button_167',
        },
        ['SHD EZ'] = {
            [34] = 'Button_30',
            [2] = 'Button_53',
            [31] = 'Button_13',
            [45] = 'Button_87',
            [1] = 'Button_31',
            [40] = 'Button_264',
            [36] = 'Button_15',
            [32] = 'Button_14',
            [51] = 'Button_90',
            [3] = 'Button_54',
            [47] = 'Button_88',
            [26] = 'Button_224',
            [30] = 'Button_217',
            [4] = 'Button_155',
            [33] = 'Button_282',
            [22] = 'Button_191',
            [20] = 'Button_203',
            [18] = 'Button_216',
            [5] = 'Button_231',
            [16] = 'Button_166',
            [15] = 'Button_214',
            [38] = 'Button_208',
        },
        ['PAL Live'] = {
            [20] = 'Button_24',
            [11] = 'Button_27',
            [1] = 'Button_26',
            [31] = 'Button_23',
            [17] = 'Button_25',
        },
        ['EZ Util'] = {
            [14] = 'Button_138',
            [2] = 'Button_33',
            [29] = 'Button_209',
            [25] = 'Button_183',
            [23] = 'Button_162',
            [8] = 'Button_185',
            [19] = 'Button_273',
            [17] = 'Button_193',
            [1] = 'Button_32',
            [6] = 'Button_39',
            [30] = 'Button_4',
            [28] = 'Button_210',
            [26] = 'Button_204',
            [24] = 'Button_164',
            [22] = 'Button_1',
            [3] = 'Button_227',
            [5] = 'Button_220',
            [16] = 'Button_192',
            [15] = 'Button_139',
            [12] = 'Button_277',
        },
        ['SHD Disc Live'] = {
            [2] = 'Button_111',
            [5] = 'Button_206',
            [4] = 'Button_115',
            [10] = 'Button_18',
            [8] = 'Button_16',
            [3] = 'Button_114',
            [7] = 'Button_112',
            [1] = 'Button_202',
            [6] = 'Button_117',
        },
        ['PAL Disc EQM'] = {
            [2] = 'Button_280',
            [5] = 'Button_62',
            [3] = 'Button_125',
            [7] = 'Button_281',
            [1] = 'Button_68',
            [4] = 'Button_71',
            [6] = 'Button_59',
        },
        ['Live Util'] = {
            [14] = 'Button_138',
            [2] = 'Button_33',
            [29] = 'Button_209',
            [27] = 'Button_37',
            [9] = 'Button_185',
            [23] = 'Button_2',
            [17] = 'Button_193',
            [1] = 'Button_32',
            [6] = 'Button_39',
            [30] = 'Button_4',
            [28] = 'Button_210',
            [12] = 'Button_277',
            [24] = 'Button_204',
            [22] = 'Button_1',
            [7] = 'Button_213',
            [20] = 'Button_273',
            [18] = 'Button_29',
            [3] = 'Button_227',
            [16] = 'Button_192',
            [15] = 'Button_139',
            [5] = 'Button_220',
        },
        ['EQM Util'] = {
            [14] = 'Button_138',
            [2] = 'Button_33',
            [12] = 'Button_277',
            [25] = 'Button_183',
            [9] = 'Button_185',
            [23] = 'Button_162',
            [8] = 'Button_61',
            [19] = 'Button_273',
            [17] = 'Button_193',
            [1] = 'Button_32',
            [6] = 'Button_39',
            [30] = 'Button_4',
            [28] = 'Button_210',
            [26] = 'Button_204',
            [24] = 'Button_164',
            [22] = 'Button_1',
            [3] = 'Button_227',
            [29] = 'Button_209',
            [16] = 'Button_192',
            [15] = 'Button_139',
            [5] = 'Button_220',
        },
        ['SHD Disc Laz'] = {
            [5] = 'Button_117',
            [3] = 'Button_115',
            [11] = 'Button_276',
            [4] = 'Button_116',
            [1] = 'Button_202',
            [6] = 'Button_167',
        },
        ['PAL Disc Live'] = {
            [13] = 'Button_103',
            [4] = 'Button_112',
            [1] = 'Button_16',
        },
        ['SHD Laz'] = {
            [34] = 'Button_208',
            [2] = 'Button_53',
            [51] = 'Button_90',
            [47] = 'Button_88',
            [37] = 'Button_216',
            [22] = 'Button_191',
            [20] = 'Button_203',
            [3] = 'Button_54',
            [31] = 'Button_13',
            [32] = 'Button_14',
            [40] = 'Button_264',
            [35] = 'Button_15',
        },
        ['Live'] = {
            [31] = 'Button_249',
            [11] = 'Button_144',
            [41] = 'Button_19',
            [9] = 'Button_141',
            [23] = 'Button_225',
            [19] = 'Button_266',
            [1] = 'Button_57',
            [40] = 'Button_3',
            [32] = 'Button_22',
            [39] = 'Button_9',
            [33] = 'Button_28',
            [20] = 'Button_70',
            [16] = 'Button_156',
            [38] = 'Button_127',
            [14] = 'Button_275',
            [12] = 'Button_145',
            [45] = 'Button_20',
            [25] = 'Button_274',
            [35] = 'Button_109',
            [21] = 'Button_43',
            [7] = 'Button_140',
            [36] = 'Button_236',
            [30] = 'Button_215',
            [43] = 'Button_50',
            [8] = 'Button_142',
            [22] = 'Button_159',
            [24] = 'Button_230',
            [17] = 'Button_157',
            [3] = 'Button_126',
            [10] = 'Button_143',
            [18] = 'Button_51',
            [15] = 'Button_146',
            [44] = 'Button_47',
        },
        ['PAL Disc Laz'] = {
            [4] = 'Button_71',
            [2] = 'Button_62',
            [5] = 'Button_58',
            [3] = 'Button_125',
            [7] = 'Button_41',
            [1] = 'Button_68',
            [8] = 'Button_40',
            [9] = 'Button_42',
        },
        ['SHD Live'] = {
            [32] = 'Button_14',
            [31] = 'Button_13',
            [4] = 'Button_5',
            [5] = 'Button_10',
            [23] = 'Button_17',
            [21] = 'Button_6',
            [36] = 'Button_15',
            [3] = 'Button_54',
            [17] = 'Button_7',
            [1] = 'Button_11',
            [2] = 'Button_53',
            [6] = 'Button_12',
        },
        ['WAR EZ'] = {
            [2] = 'Button_89',
            [31] = 'Button_282',
            [12] = 'Button_115',
            [7] = 'Button_184',
            [32] = 'Button_30',
            [6] = 'Button_31',
        },
        ['PAL Laz'] = {
            [7] = 'Button_184',
            [2] = 'Button_89',
            [12] = 'Button_115',
        },
        ['Laz Tank'] = {
            [14] = 'Button_242',
            [13] = 'Button_237',
            [5] = 'Button_270',
            [4] = 'Button_269',
            [9] = 'Button_80',
            [2] = 'Button_272',
            [7] = 'Button_34',
            [1] = 'Button_271',
            [15] = 'Button_268',
            [6] = 'Button_200',
        },
        ['WAR Disc EZ'] = {
            [3] = 'Button_125',
        },
        ['EZ Tank'] = {
            [14] = 'Button_242',
            [2] = 'Button_272',
            [5] = 'Button_270',
            [4] = 'Button_269',
            [9] = 'Button_80',
            [13] = 'Button_237',
            [7] = 'Button_34',
            [1] = 'Button_271',
            [15] = 'Button_268',
            [6] = 'Button_200',
        },
    },
}
